[[entries]]
group = "config"
relative_path = "atuin"
digest = "7e3d44bdfa3f3cb3efe837270322864d6a6bb520bd337f7a7a23d2f547886934"
size = 0
mode = 448
mtime_ns = 1762524808257809893
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "brave-flags.conf"
digest = "87c1f59d73e32b07ddabeeeb9589c1a4cfd1067298a9235884676c3171378d77"
size = 1079
mode = 420
mtime_ns = 1760314782110733826
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "captive-browser.toml"
digest = "1bc05e753567f1d4656e002e42fcaa129aaecfe0d01cceb408de6c32f3c967de"
size = 1391
mode = 420
mtime_ns = 1753794607555628122
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "dconf"
digest = "3867b68a0c42822bfa3c5fac4757849fe6812986deb8f19431a0623312b3472d"
size = 0
mode = 448
mtime_ns = 1764010832513584080
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "dunst"
digest = "9afb3a38f54bfa5fa0d3d561d3d5a3b1ba2681eae8dda79a9eff73970883b0cd"
size = 0
mode = 493
mtime_ns = 1726583841620755773
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "environment.d"
digest = "3a2ddba4b1ec11f4acba24dced5ce0a96cdb23ebd33484763cdf0779a919dfd7"
size = 0
mode = 493
mtime_ns = 1755982090553521694
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "eww"
digest = "76283a5cc22080bc960e3a6425595ce4549c9e18f98e1ef6dc9e0450e68a6780"
size = 0
mode = 493
mtime_ns = 1763924192328612959
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "hypr"
digest = "19b84b464134c8bb35051c3f160193bb7d60da2c0e18e4ee0c16842ed4538303"
size = 0
mode = 493
mtime_ns = 1764010832514685442
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "kitty"
digest = "e8652a6152598d5b70c4f10c5d907b60e2d3e1a840f3c5043edbb888cb9fc2fd"
size = 0
mode = 493
mtime_ns = 1761894574951897467
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "metapac"
digest = "f0d9982a00c8a983c3209225d12a625b3a27f23d5719493d2f43d4b6576950ed"
size = 0
mode = 493
mtime_ns = 1734800605446007639
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "micro/colorschemes"
digest = "67daaf2a46c5b588b31e46557d00c9eb4da6095204e52b9d3316b981504d56cb"
size = 0
mode = 493
mtime_ns = 1763315723482907984
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "micro/settings.json"
digest = "4ec9d518dfd87127e4c7de6bb24e9fb164b48345d88695a1ab4d6ecf31c783e6"
size = 77
mode = 420
mtime_ns = 1763315758018431575
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "nautilus"
digest = "6662b8ab4cab4ebfaf0303f8fd7a3cca78d4b52f089917095b11d291d6aab626"
size = 0
mode = 493
mtime_ns = 1750845998470736787
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "quickshell"
digest = "5e4217614742bfe25e4652d6c29a79859ccc27caa0a99fac9592e073d6a839df"
size = 0
mode = 493
mtime_ns = 1764007249669746623
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "rofi"
digest = "7b0ecb3afa011f1597de0f83d009ccc6ec190264bef0b9b68a908f0f9cffd106"
size = 0
mode = 493
mtime_ns = 1757583723402347207
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "swaync"
digest = "a44dec6e9a2d1507002eb7755fb94b6147604669f4e7bfd779c16a05844d8dae"
size = 0
mode = 493
mtime_ns = 1764010832512584168
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "sys64"
digest = "2c22f2f775a36bb044ca2a7da076e68a46376b063543b50c1ef0d23dd08b2659"
size = 0
mode = 493
mtime_ns = 1763151283463598577
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "systemd"
digest = "aadddc844178f85b4ace92526b939d43da3243c4de447718b4e99d903b00ee29"
size = 0
mode = 493
mtime_ns = 1762773703928963989
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "user-dirs.dirs"
digest = "3c09bac1adbaca469fdba6e5b78bad0b456006c8b36bfa1f6053072b2891e5f6"
size = 627
mode = 384
mtime_ns = 1756822105149935114
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "user-dirs.locale"
digest = "e7ab2bfee30a493f2a2ca591c42c7d9ecbf876fa6673473a17aeb5712ca7a54f"
size = 5
mode = 420
mtime_ns = 1725727791402929114
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "uwsm"
digest = "9be9725d28e6eb6382e02ac80b591c04772fcf07fe81b77d60df2b3494ad2375"
size = 0
mode = 493
mtime_ns = 1741888631159073016
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "vicinae"
digest = "6b6d34dce3b7ab726a21cc49ac16cc6bb5597e908769e4c3e1cf3c13e21caff5"
size = 0
mode = 493
mtime_ns = 1762871721304391900
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "waybar"
digest = "beb9d3ce73f7f17cea9a481a4cba4a851bbf2d4a9d378da9ca2709461c4aa920"
size = 0
mode = 493
mtime_ns = 1764010832514685442
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "etc"
relative_path = "brave/policies/managed"
digest = "0092635b386f5843086a2f8973aca4fc753d6f6979f0288c2f572e8f6ea5b334"
size = 0
mode = 493
mtime_ns = 1762730382565785758
type = "directory"
uid = 0
gid = 0

[[entries]]
group = "home"
relative_path = "Templates"
digest = "b3bae66d9725825844768d96b74495659eef11492ffc2d760f882331ecf35154"
size = 0
mode = 493
mtime_ns = 1756766499670253197
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "local"
relative_path = "bin/custom"
digest = "28e8de5fbb1eab30d30f5f0d226b923691085280eecd741dcbb215d73c9d5be1"
size = 0
mode = 493
mtime_ns = 1760317443926437668
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "local"
relative_path = "share/applications"
digest = "1b649506daa0d45bbcd803e71c435d9985de9e7a8295290df3f40c5074f1b390"
size = 0
mode = 448
mtime_ns = 1764010832513584080
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "local"
relative_path = "share/icons/hicolor/48x48/apps/typst.png"
digest = "e691e19689b38dfcba51006ec1bf7bab54f95b0ecc0b427f25d127f549d43aac"
size = 16532
mode = 420
mtime_ns = 1761946144104377696
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "local"
relative_path = "share/icons/hicolor/48x48/apps/whatsapp.png"
digest = "8e4dfe43bcd4f78f5cd046bebdfc15b308d8a4906995c4d91bab49c18cb71504"
size = 2501
mode = 420
mtime_ns = 1761946144104377696
type = "file"
uid = 1000
gid = 1000
