[[entries]]
group = "config"
relative_path = "atuin"
digest = "ffd0d5f881098339904c3a9235d3d44f2426bbb7e4110ac46e3f0a1a4ae4cbf8d88bdbcfd7cad4f380b75a931b41bd42b2ff6531953a319f54c879cbe8b0f0f2"
size = 0
mode = 448
mtime_ns = 1762524808257809893
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "brave-flags.conf"
digest = "4dcc9bd45d5fed980e49db27c9937cdbbe5407b9d6102533d66941d595ce0e78e331e32117e7bdb151b010fa7e5946c005eaf67ca7be867552c9b55bfcb35695"
size = 1079
mode = 420
mtime_ns = 1765537184890392183
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "captive-browser.toml"
digest = "80d2d1bde204b835a18515a2cc98f6a1eb9c0bb16caba84abd46f6e5414b32ddf79211a26df5f81aea36e6101e224acd7bf36924801f30d41478bd6f90279d9f"
size = 1391
mode = 420
mtime_ns = 1753794607555628122
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "dconf"
digest = "bee862b8a2fd707ba9fefdc885b9c938c18068ceaf8a72e6d0ded7cf6c4db30a68c0b200242af18e0b0655289dba6e3fe3dd8fa128a615a86e25c49ef42103dd"
size = 0
mode = 448
mtime_ns = 1767183963643636935
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "dunst"
digest = "a9cb65521cee4e908a6040777ed27b2954c083f4df2bce84b9d6f0c234ec57dc3535afb8926343e316baba072ae74d11ee5674a373ae5bc2b8284b45806f2e11"
size = 0
mode = 493
mtime_ns = 1765537184891392178
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "environment.d"
digest = "cdb6c71b90d538b9fd485d8c74f26739fbc79a137a55a44f571bdf6dfa4fbc6edf6ed9a5b7455ef19da8f0c695e9ee7df0f5b0950e49e045b760ea7312ef39d4"
size = 0
mode = 493
mtime_ns = 1765537184891392178
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "hypr"
digest = "38093fd152a89915a37e6b33404aa7eb11ff054bc0da346f11af81481cc46687aff3523e1ac09ae2fb90c1717036ba177991613f068ac718facf1da5ceaf688a"
size = 0
mode = 493
mtime_ns = 1766918831348144187
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "kitty"
digest = "144152202fc9793ad1ded8fb0bdae09021ed7d498dabea7fb9f1a2191a801d98a36b57c25d6a9a4e3b74bebe2b698049ef9af91ac549ad2230302e21eddd20e7"
size = 0
mode = 493
mtime_ns = 1761894574951897467
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "metapac"
digest = "c8498d7898a92da5964c262bd1423c836b469c880d150e04a5d3a4f925e24313cd3384be074cae013c2acbbcff95c4f32b45866da4594195cd463c3719722bb0"
size = 0
mode = 493
mtime_ns = 1734800605446007639
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "micro/colorschemes"
digest = "fd59f202c448e633205bd8f2c134e73697159d6e94c433da68f28eab4bc6add4dd75487d997efbd30a69d0292d7ef03e412981c29c7c7520ca0c83e4e67f155d"
size = 0
mode = 493
mtime_ns = 1763315723482907984
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "micro/settings.json"
digest = "217144d1ddc24c93c5db36903e886f4f846682352d0e040bafcabf9bb4e72a2f1a2ec28d32b703f9e78009639fc16fa72e2c63b7b68092a96757cc9bc4a26012"
size = 77
mode = 420
mtime_ns = 1763315758018431575
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "nautilus"
digest = "87e2dac3e4e0d68b510bd931959cdd9fed2f635af1d8a7d92e0f81fb46cde571efa604e2433ff635c4fa715fcb9115e1f603ede68779c2783c24f2b5dc57be67"
size = 0
mode = 493
mtime_ns = 1750845998470736787
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "quickshell"
digest = "2df02bceddd7a893b8cb1fc9a863874eea655866d2773292e4fd7aee491a5b9fd511055071aee783eae9f35c361756b57ccd2acd7a20a1df4ab60339e133daf5"
size = 0
mode = 493
mtime_ns = 1767110072537373519
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "rofi"
digest = "ae6271e8e2769634a70c35b5a4c6c11dfc8e3bf99e1b291d76ed91a5ccc70e90b1122ef8281b65da11d5218439d96a1622857e671fcd6f6cac5e847ce36baf1a"
size = 0
mode = 493
mtime_ns = 1757583723402347207
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "swaync"
digest = "fde1ba0b3d782842e71ee1af158f0a41c8bc4e57d20b48e604e573ed5ff8aa0c63d3f8fc6b16f3299dbd10e9f41cdf07a19be4598db2f46e9230649c5e05b907"
size = 0
mode = 493
mtime_ns = 1765537184895392161
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "sys64"
digest = "aa30e4fd51fa0e3f4cfb72e1edc553e288a10b10e1ccda99d66891289a352951b79297259bec71836cccb6c1ad76cc7e10a944e1e1c97249a36893be8de89907"
size = 0
mode = 493
mtime_ns = 1763151283463598577
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "systemd"
digest = "6468abd6661e118f2c237462c6da0bf79b2abcbb1d351d8a5f929f023a9b9d600cd76831a36dc6650fbc986c70255373636b290c2b981624a765d601e8608e13"
size = 0
mode = 493
mtime_ns = 1762773703928963989
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "user-dirs.dirs"
digest = "88cd2b4f8005657dbd7c1213bd0b9c5cf88cc32d22dd585e4aace824908c090f93e0e61336fa0faf22080db419158182edc9e40bb2c55e7fe02192260264b520"
size = 627
mode = 420
mtime_ns = 1765537184896392157
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "user-dirs.locale"
digest = "6cc891a5f8e42dbeced3926d158e36f2cbb2b5b1337c6cdc15c9c69867eb0541418a7600603d5e3207e113e7465879c0fed91515640b21f6c657eb03aacc349e"
size = 5
mode = 420
mtime_ns = 1725727791402929114
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "uwsm"
digest = "fa6cd19bfe59601b0aaaeaa02075d62b70dd3a9faeaada374ea7fb1dcc3eae99317672db334af966d2e58115d240984c2acfafb5deb28596940fa71eb1abdf7f"
size = 0
mode = 493
mtime_ns = 1741888631159073016
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "vicinae"
digest = "081dc77f9a96c273c7b8198617b081cae8367bcc2df9994c774ec91642fe4c8ae539cbbe26df54cd4be671be205302588c9488eaa86d1faf472a7e9eee09df4a"
size = 0
mode = 493
mtime_ns = 1766352989219725337
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "waybar"
digest = "c9e7f5ef8a8ce7933567a0dba24efc8a38fb50ef933052186a331cb086df6f629a6f9ccadd1830a1e85c02870c834e1b83516097251d1f2f761d1ff17c3c5ac5"
size = 0
mode = 493
mtime_ns = 1766564625482323248
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "etc"
relative_path = "brave/policies/managed"
digest = "0092635b386f5843086a2f8973aca4fc753d6f6979f0288c2f572e8f6ea5b334"
size = 0
mode = 493
mtime_ns = 1762730382565785758
type = "directory"
uid = 0
gid = 0

[[entries]]
group = "home"
relative_path = "Templates"
digest = "d47f84c1fe2d9efafa6ed1dac9d578cac06afc92d2dbdbd4c2e8440da500fc02626cd985660c19f00743ffadb0e544ad0409836ade87c3bb9dcdb579e1b131a8"
size = 0
mode = 493
mtime_ns = 1756766499670253197
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "local"
relative_path = "bin"
digest = "397730bc791d8b89a2abc5d6ec6e5b62787a8fd23d72e7de7b97aa17d3acb809555034b744c7dd90f9b830c1e49dbd75cb9203148ebcfafb080a870057eb4898"
size = 0
mode = 493
mtime_ns = 1767184145150844344
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "local"
relative_path = "share/applications"
digest = "1142928965224744b4b2f11f60c22550ef451a7b0b29b5fb4c5e22b0215fff40958507d04081a02ec82ceb0452447a89fb7559b76713432e5793378747db8255"
size = 0
mode = 448
mtime_ns = 1766649476629616945
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "local"
relative_path = "share/icons/Adwaita"
digest = "93d787a26681c9f248765d4842a89da68da83ebda24f22d24f82059aae966ea2143d5679d7fce4214e2114c9bc5e3f4ab3470f8c65a564c997eab573b48f0ab6"
size = 0
mode = 493
mtime_ns = 1767184498672347269
type = "directory"
uid = 1000
gid = 1000
