[[entries]]
group = "config"
relative_path = "atuin"
digest = "7e3d44bdfa3f3cb3efe837270322864d6a6bb520bd337f7a7a23d2f547886934"
size = 0
mode = 448
mtime_ns = 1762524808257809893
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "brave-flags.conf"
digest = "87c1f59d73e32b07ddabeeeb9589c1a4cfd1067298a9235884676c3171378d77"
size = 1079
mode = 420
mtime_ns = 1760314782110733826
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "captive-browser.toml"
digest = "1bc05e753567f1d4656e002e42fcaa129aaecfe0d01cceb408de6c32f3c967de"
size = 1391
mode = 420
mtime_ns = 1753794607555628122
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "dconf"
digest = "e69a1a1aed44da943c8d97faba19651b7ebecd60f9a15d318df3df83149151fa"
size = 0
mode = 448
mtime_ns = 1763151102640806342
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "dunst"
digest = "9afb3a38f54bfa5fa0d3d561d3d5a3b1ba2681eae8dda79a9eff73970883b0cd"
size = 0
mode = 493
mtime_ns = 1726583841620755773
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "environment.d"
digest = "3a2ddba4b1ec11f4acba24dced5ce0a96cdb23ebd33484763cdf0779a919dfd7"
size = 0
mode = 493
mtime_ns = 1755982090553521694
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "eww"
digest = "78fb4045624b7eafd936ac95b596337f08b6f73ca7dcae46c09b4c9be8a01431"
size = 0
mode = 493
mtime_ns = 1745402326976587224
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "hypr"
digest = "bb84ef458cacf12b2c92e5bc1213058c857a5ba2b6b7353950defddbe36871b7"
size = 0
mode = 493
mtime_ns = 1763100821002232551
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "kitty"
digest = "e8652a6152598d5b70c4f10c5d907b60e2d3e1a840f3c5043edbb888cb9fc2fd"
size = 0
mode = 493
mtime_ns = 1761894574951897467
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "metapac"
digest = "f0d9982a00c8a983c3209225d12a625b3a27f23d5719493d2f43d4b6576950ed"
size = 0
mode = 493
mtime_ns = 1734800605446007639
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "nautilus"
digest = "6662b8ab4cab4ebfaf0303f8fd7a3cca78d4b52f089917095b11d291d6aab626"
size = 0
mode = 493
mtime_ns = 1750845998470736787
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "rofi"
digest = "7b0ecb3afa011f1597de0f83d009ccc6ec190264bef0b9b68a908f0f9cffd106"
size = 0
mode = 493
mtime_ns = 1757583723402347207
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "swaync"
digest = "8fc80a0ad1753c14a7f68e58fe6f128d01f006347e4c2723577507dc54ac4f38"
size = 0
mode = 493
mtime_ns = 1762520559366167572
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "sys64"
digest = "2c22f2f775a36bb044ca2a7da076e68a46376b063543b50c1ef0d23dd08b2659"
size = 0
mode = 493
mtime_ns = 1763151283463598577
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "systemd"
digest = "5912eb68545834c9901342d8e0bd796082f2d1c57dbef2ea78822ef5ea3ffaf5"
size = 0
mode = 493
mtime_ns = 1762773703928963989
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "user-dirs.dirs"
digest = "3c09bac1adbaca469fdba6e5b78bad0b456006c8b36bfa1f6053072b2891e5f6"
size = 627
mode = 384
mtime_ns = 1756822105149935114
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "user-dirs.locale"
digest = "e7ab2bfee30a493f2a2ca591c42c7d9ecbf876fa6673473a17aeb5712ca7a54f"
size = 5
mode = 420
mtime_ns = 1725727791402929114
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "uwsm"
digest = "9be9725d28e6eb6382e02ac80b591c04772fcf07fe81b77d60df2b3494ad2375"
size = 0
mode = 493
mtime_ns = 1741888631159073016
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "vicinae"
digest = "a4f60ade64dbe27f17c5bc36a01b20ade8a5a8fb72b9515945a60fa088ac085d"
size = 0
mode = 493
mtime_ns = 1762871721304391900
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "config"
relative_path = "waybar"
digest = "ffc922fb6a4d067d70ac5cbfb672781af80c68fc35b431a96936248579946a46"
size = 0
mode = 493
mtime_ns = 1762773703932595238
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "home"
relative_path = "Templates"
digest = "b3bae66d9725825844768d96b74495659eef11492ffc2d760f882331ecf35154"
size = 0
mode = 493
mtime_ns = 1756766499670253197
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "local"
relative_path = "bin/custom"
digest = "8ae313be0f7738b03b02ac9783dff64b86b471b2737264b44a77fb213f083b58"
size = 0
mode = 493
mtime_ns = 1760317443926437668
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "local"
relative_path = "share/applications"
digest = "64802b551c064111b5fa688b39b478f25820cbe33cc22cfbc3fb4f80c8cc6776"
size = 0
mode = 448
mtime_ns = 1761939724624330816
type = "directory"
uid = 1000
gid = 1000

[[entries]]
group = "local"
relative_path = "share/icons/hicolor/48x48/apps/typst.png"
digest = "e691e19689b38dfcba51006ec1bf7bab54f95b0ecc0b427f25d127f549d43aac"
size = 16532
mode = 420
mtime_ns = 1761946144104377696
type = "file"
uid = 1000
gid = 1000

[[entries]]
group = "local"
relative_path = "share/icons/hicolor/48x48/apps/whatsapp.png"
digest = "8e4dfe43bcd4f78f5cd046bebdfc15b308d8a4906995c4d91bab49c18cb71504"
size = 2501
mode = 420
mtime_ns = 1761946144104377696
type = "file"
uid = 1000
gid = 1000
